name: Publish NuGet

on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  nuget:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Create and push NuGet package
        run: |
          dotnet pack -c Release -o nuget -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg
          dotnet nuget push nuget/**/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate